import numpy as np
A =  np.array([[1],[-1]])
B =  np.array([[-4],[6]])
C =  np.array([[-3],[-5]])
a = np.linalg.norm(C - B)
b= np.linalg.norm(A - C)
c= np.linalg.norm(B - A)
arr_1 = np.array([[0,1,1],[1,0,1],[1,1,0]])
arr_2 = np.array([a,b,c])
print(np.linalg.solve(arr_1,arr_2))
